# example config file for a livekit server

port: 7880
log_level: info
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  # use_external_ip should be set to true for most cloud environments where
  # the host has a public IP address, but is not exposed to the process.
  # LiveKit will attempt to use STUN to discover the true IP, and advertise
  # that IP with its clients
  use_external_ip: true

keys:
  admin: "admin"

webhook:
  api_key: "admin" # must match the key used by equinox
  urls:
    - "http://localhost:4000/v1/portal" # equinox